{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 240,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Importing the packages\n",
    "\n",
    "from pycatia import catia\n",
    "from pycatia.mec_mod_interfaces.part_document import PartDocument\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 241,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Making the Catia instance\n",
    "\n",
    "caa = catia()\n",
    "application = caa.application\n",
    "documents = application.documents\n",
    "\n",
    "# Closing if any document is open\n",
    "if documents.count > 0:\n",
    "    for document in documents:\n",
    "        document.close()\n",
    "        \n",
    "# Create Part\n",
    "documents.add('Part')\n",
    "\n",
    "# Get references to document, parts and tools to create geometries\n",
    "document: PartDocument = application.active_document        # Get active document\n",
    "part = document.part                                        # Get Part\n",
    "partbody = part.bodies[0]                                   # Get default PartBody by index\n",
    "# partbody = part.bodies.item(\"PartBody\")                   # Get default PartBody by name\n",
    "sketches = partbody.sketches                                # Get sketches on PartBody \n",
    "hybrid_bodies = part.hybrid_bodies                          # Get Hybrid Bodies \n",
    "hsf = part.hybrid_shape_factory                             # Get Hybrid Shape Factory \n",
    "shpfac = part.shape_factory                                 # Get Shape Factory \n",
    "selection = document.selection                              # Get document selection"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 242,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get references to main planes\n",
    "\n",
    "plane_XY = part.origin_elements.plane_xy\n",
    "plane_YZ = part.origin_elements.plane_yz\n",
    "plane_ZX = part.origin_elements.plane_zx"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 243,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a new HybridBody to hold the construction elements\n",
    "\n",
    "construction_elements = hybrid_bodies.add()\n",
    "construction_elements.name = \"construction_elements\"\n",
    "\n",
    "# Create a global reference point\n",
    "p_0 = hsf.add_new_point_coord(0, 0, 0)\n",
    "p_0.name = \"p_0\"\n",
    "construction_elements.append_hybrid_shape(p_0)\n",
    "\n",
    "# Create a point in Z axis\n",
    "p_z = hsf.add_new_point_coord(0, 0, 1)\n",
    "p_z.name = \"p_z\"\n",
    "construction_elements.append_hybrid_shape(p_z)\n",
    "\n",
    "# Z dir\n",
    "z_dir = hsf.add_new_line_pt_pt(p_0,p_z)\n",
    "z_dir.name = \"z_dir\"\n",
    "construction_elements.append_hybrid_shape(z_dir)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 244,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Set PartBody as a working object\n",
    "part.in_work_object = partbody\n",
    "\n",
    "# Shaft radius\n",
    "shaft_radius = 1\n",
    "\n",
    "# Create sketch in plane_XY\n",
    "sketch_1 = sketches.add(plane_XY)\n",
    "sketch_1.name = \"Shaft_sketch\"\n",
    "\n",
    "# Sketch open edition\n",
    "ske2D_1 = sketch_1.open_edition()\n",
    "\n",
    "circle1 = ske2D_1.create_closed_circle(0, 0, shaft_radius)\n",
    "\n",
    "# sketch close edition\n",
    "sketch_1.close_edition()\n",
    "\n",
    "# Adding pad to the sketch to make a 3D part\n",
    "shaft_top = shpfac.add_new_pad(sketch_1, 10)\n",
    "shaft_top.name = \"Shaft_top\"\n",
    "\n",
    "# Update the document\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 245,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Add blades\n",
    "\n",
    "sketch_2 = sketches.add(plane_ZX)\n",
    "sketch_2.name = \"Blade_sketch\"\n",
    "ske2D_2 = sketch_2.open_edition()\n",
    "\n",
    "# Blade points\n",
    "s2p1 = (6, -1)\n",
    "s2p2 = (7.5, 1.5)\n",
    "s2p3 = (8, 1)\n",
    "s2p4 = (6.5, -1.5)\n",
    "\n",
    "ske2D_2.create_line(*s2p1,*s2p2)\n",
    "ske2D_2.create_line(*s2p2,*s2p3)\n",
    "ske2D_2.create_line(*s2p3,*s2p4)\n",
    "ske2D_2.create_line(*s2p4,*s2p1)\n",
    "\n",
    "sketch_2.close_edition()\n",
    "\n",
    "blade = shpfac.add_new_pad(sketch_2, 56.4)\n",
    "blade.name = \"Single_blade\"\n",
    "\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 246,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Circular pattern for blades\n",
    "# Create an angular pattern around Z axis\n",
    "\n",
    "# add_new_rect_pattern arguments:\n",
    "# i_shape_to_copy : blade\n",
    "# i_nb_of_copies_in_radial_dir : 1\n",
    "# i_nb_of_copies_in_angular_dir : 5\n",
    "# i_step_in_radial_dir : 0 mm\n",
    "# i_step_in_angular_dir : 360/5 deg\n",
    "# i_shape_to_copy_position_along_radial_dir : 1 (to leave a space between patterns)\n",
    "# i_shape_to_copy_position_along_angular_dir : 1 (to leave a space between patterns)\n",
    "# i_rotation_center : z_dir\n",
    "# i_rotation_axis : z_dir\n",
    "# i_is_reversed_rotation_axis : True\n",
    "# i_rotation_angle : 0\n",
    "# i_is_radius_aligned : True\n",
    "\n",
    "# Create circular pattern around Z axis\n",
    "blades = shpfac.add_new_circ_pattern(blade, 1, 5, 0, 360/5, 1, 1, z_dir, z_dir, True, 0, True)\n",
    "blades.name = \"Blades\"\n",
    "\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 247,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Making the body\n",
    "\n",
    "#Sketching spline for the body\n",
    "sketch_3 = sketches.add(plane_ZX)\n",
    "sketch_3.name = \"Body_sketch\"\n",
    "\n",
    "skbody = sketch_3.open_edition()\n",
    "\n",
    "s3p1 = skbody.create_control_point(-10, 28)\n",
    "s3p2 = skbody.create_control_point(-6, 26)\n",
    "s3p3 = skbody.create_control_point(0, 0)\n",
    "s3p4 = skbody.create_control_point(-10, -35)\n",
    "s3_points = [s3p1, s3p2, s3p3, s3p4]\n",
    "\n",
    "spline = skbody.create_spline(s3_points)\n",
    "mid_line = skbody.create_line(-10, 28, -10, -35)\n",
    "\n",
    "sketch_3.close_edition()\n",
    "\n",
    "# Create a global reference point\n",
    "ra_p1 = hsf.add_new_point_coord(20, 0, -10)\n",
    "ra_p1.name = \"p1\"\n",
    "construction_elements.append_hybrid_shape(ra_p1)\n",
    "\n",
    "# Create a global reference point\n",
    "ra_p2 = hsf.add_new_point_coord(-30, 0, -10)\n",
    "ra_p2.name = \"p2\"\n",
    "construction_elements.append_hybrid_shape(ra_p2)\n",
    "\n",
    "# Add revolution axis\n",
    "rev_axis = hsf.add_new_line_pt_pt(ra_p1,ra_p2)\n",
    "rev_axis.name = \"body_revolution_axis\"\n",
    "construction_elements.append_hybrid_shape(rev_axis)\n",
    "\n",
    "document.part.update()\n",
    "\n",
    "# Making the shaft and updating document\n",
    "main_body = shpfac.add_new_shaft(sketch_3)\n",
    "main_body.revolute_axis = rev_axis\n",
    "main_body.name = \"Main_Body\"\n",
    "\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 248,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Creating the tail\n",
    "\n",
    "# Making new reference plane for sketching ellipse for the tail profile\n",
    "plane_ref = hsf.add_new_plane_offset(plane_YZ, -25, False)\n",
    "construction_elements.append_hybrid_shape(plane_ref)\n",
    "plane_ref.name = \"Tail_sketch_plane\"\n",
    "\n",
    "document.part.update()\n",
    "\n",
    "sketch_4 = sketches.add(plane_ref)\n",
    "sketch_4.name = \"Tail_sketch\"\n",
    "\n",
    "tail = sketch_4.open_edition()\n",
    "ellipse = tail.create_closed_ellipse(0, -10, 0, 0, 1.5, 3)\n",
    "sketch_4.close_edition()\n",
    "\n",
    "tail_pad = shpfac.add_new_pad(sketch_4, -50)\n",
    "tail_pad.name = \"Tail\"\n",
    "\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 249,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Producing the horizontal stabilizer\n",
    "\n",
    "sketch_5 = sketches.add(plane_ZX)\n",
    "sketch_5.name = \"Horizontal_stabilizer_sketch\"\n",
    "stabilizer = sketch_5.open_edition()\n",
    "\n",
    "s5p1 = (-7, -60)\n",
    "s5p2 = (-7, -65)\n",
    "s5p3 = (-6, -65)\n",
    "s5p4 = (-6, -60)\n",
    "\n",
    "stabilizer.create_line(*s5p1, *s5p2)\n",
    "stabilizer.create_line(*s5p2, *s5p3)\n",
    "stabilizer.create_line(*s5p3, *s5p4)\n",
    "stabilizer.create_line(*s5p4, *s5p1)\n",
    "\n",
    "sketch_4.close_edition()\n",
    "\n",
    "hstabilizer = shpfac.add_new_pad(sketch_5, 10)\n",
    "hstabilizer.name = \"Horizontal_stabilizer\"\n",
    "hstabilizer_2 = shpfac.add_new_pad(sketch_5, -10)\n",
    "hstabilizer_2.name = \"Horizontal_stabilizer\"\n",
    "\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 250,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Making the vertical Stabilizer\n",
    "\n",
    "sketch_6 = sketches.add(plane_ZX)\n",
    "sketch_6.name = \"Vertical_stabilizer_sketch\"\n",
    "stabilizer = sketch_6.open_edition()\n",
    "\n",
    "s6p1 = (-13, -72)\n",
    "s6p2 = (-7, -72)\n",
    "s6p3 = (2, -80)\n",
    "s6p4 = (2, -85)\n",
    "s6p5 = (-13, -82)\n",
    "\n",
    "stabilizer.create_line(*s6p1, *s6p2)\n",
    "stabilizer.create_line(*s6p2, *s6p3)\n",
    "stabilizer.create_line(*s6p3, *s6p4)\n",
    "stabilizer.create_line(*s6p4, *s6p5)\n",
    "stabilizer.create_line(*s6p5, *s6p1)\n",
    "\n",
    "\n",
    "sketch_6.close_edition()\n",
    "\n",
    "vstabilizer = shpfac.add_new_pad(sketch_6, 1.5)\n",
    "vstabilizer.name = \"Vertical_stabilizer\"\n",
    "vstabilizer_2 = shpfac.add_new_pad(sketch_6, -1.5)\n",
    "vstabilizer_2.name = \"Vertical_stabilizer\"\n",
    "\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 251,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Rear fan shaft\n",
    "\n",
    "rear_fan_radius = 0.5\n",
    "\n",
    "sketch_7 = sketches.add(plane_ZX)\n",
    "sketch_7.name = \"Shaft_rear_sketch\"\n",
    "\n",
    "r_shaft = sketch_7.open_edition()\n",
    "circle1 = r_shaft.create_closed_circle(0, -82.5, rear_fan_radius)\n",
    "sketch_7.close_edition()\n",
    "\n",
    "shaft_rear = shpfac.add_new_pad(sketch_7, 4)\n",
    "shaft_rear.name = \"Shaft_rear\"\n",
    "\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 252,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Add rear blades\n",
    "\n",
    "sketch_8 = sketches.add(plane_XY)\n",
    "sketch_8.name = \"Blade_rear_sketch\"\n",
    "r_blade_sketch = sketch_8.open_edition()\n",
    "\n",
    "s8p1 = (-82.1, 3)\n",
    "s8p2 = (-82.2, 3.3)\n",
    "s8p3 = (-82.9, 3)\n",
    "s8p4 = (-82.8, 2.8)\n",
    "\n",
    "r_blade_sketch.create_line(*s8p1,*s8p2)\n",
    "r_blade_sketch.create_line(*s8p2,*s8p3)\n",
    "r_blade_sketch.create_line(*s8p3,*s8p4)\n",
    "r_blade_sketch.create_line(*s8p4,*s8p1)\n",
    "\n",
    "sketch_7.close_edition()\n",
    "\n",
    "blade_rear = shpfac.add_new_pad(sketch_8, 8)\n",
    "blade_rear.name = \"Single_blade_rear\"\n",
    "\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 253,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create an angular pattern around shaft axis\n",
    "\n",
    "p_rear_center = hsf.add_new_point_coord(-82.5, 0, 0)\n",
    "p_rear_center.name = \"p_rear_center\"\n",
    "construction_elements.append_hybrid_shape(p_rear_center)\n",
    "\n",
    "p_y = hsf.add_new_point_coord(-82.5, 1, 0)\n",
    "p_y.name = \"p_y\"\n",
    "construction_elements.append_hybrid_shape(p_y)\n",
    "\n",
    "shaft_dir = hsf.add_new_line_pt_pt(p_rear_center,p_y)\n",
    "shaft_dir.name = \"shaft_dir\"\n",
    "construction_elements.append_hybrid_shape(shaft_dir)\n",
    "\n",
    "document.part.update()\n",
    "\n",
    "# add_new_rect_pattern arguments:\n",
    "# i_shape_to_copy : blade\n",
    "# i_nb_of_copies_in_radial_dir : 1\n",
    "# i_nb_of_copies_in_angular_dir : 4\n",
    "# i_step_in_radial_dir : 0 mm\n",
    "# i_step_in_angular_dir : 360/4 deg\n",
    "# i_shape_to_copy_position_along_radial_dir : 1 (to leave a space between patterns)\n",
    "# i_shape_to_copy_position_along_angular_dir : 1 (to leave a space between patterns)\n",
    "# i_rotation_center : shaft_dir\n",
    "# i_rotation_axis : shaft_dir\n",
    "# i_is_reversed_rotation_axis : True\n",
    "# i_rotation_angle : 0\n",
    "# i_is_radius_aligned : True\n",
    "\n",
    "# Create circular pattern around Z axis\n",
    "blades_rear = shpfac.add_new_circ_pattern(blade_rear, 1, 4, 0, 90, 1, 1, shaft_dir, shaft_dir, True, 0, True)\n",
    "blades_rear.name = \"Blades_rear\"\n",
    "\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 254,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Landing gear\n",
    "\n",
    "sketch_9 = sketches.add(plane_ZX)\n",
    "sketch_9.name = \"Landing_gear_sketch\"\n",
    "\n",
    "landing_gear_sketch = sketch_9.open_edition()\n",
    "\n",
    "landing_gear_radius = 1\n",
    "landing_gear_sketch.create_closed_circle(-10, -3, landing_gear_radius)\n",
    "\n",
    "sketch_9.close_edition()\n",
    "\n",
    "document.part.update()\n",
    "\n",
    "# Create a curve\n",
    "landing_gear_path = hsf.add_new_spline()\n",
    "landing_gear_path.name = \"Landing_gear_path\"\n",
    "landing_gear_path.add_point(hsf.add_new_point_coord(-3, 0, -10))\n",
    "landing_gear_path.add_point(hsf.add_new_point_coord(-10, 8, -15))\n",
    "landing_gear_path.add_point(hsf.add_new_point_coord(-15, 15, -25))\n",
    "landing_gear_path.add_point(hsf.add_new_point_coord(0, 15, -25))\n",
    "landing_gear_path.add_point(hsf.add_new_point_coord(15, 15, -25))\n",
    "landing_gear_path.add_point(hsf.add_new_point_coord(10, 8, -15))\n",
    "landing_gear_path.add_point(hsf.add_new_point_coord(3, 0, -10))\n",
    "\n",
    "# Append guide splines \n",
    "construction_elements.append_hybrid_shape(landing_gear_path)\n",
    "    \n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 255,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a rib\n",
    "\n",
    "# Reference to sketch\n",
    "ref_sketch_9 = part.create_reference_from_object(sketch_9) \n",
    "rib1 = shpfac.add_new_rib_from_ref(ref_sketch_9, landing_gear_path)\n",
    "rib1.name = \"Landing_gear\"\n",
    "\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 256,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Getting the landing gear for the other side\n",
    "\n",
    "landing_gears = shpfac.add_new_circ_pattern(rib1, 1, 2, 0, 180, 1, 1, z_dir, z_dir, True, 0, True)\n",
    "landing_gears.name = \"Landing_gears\"\n",
    "\n",
    "document.part.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 257,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Zoom in and save the document\n",
    "\n",
    "active_viewer = caa.active_window.active_viewer\n",
    "active_viewer.zoom_in()\n",
    "\n",
    "# Hiding the construction elements\n",
    "selection.clear()\n",
    "selection.add(construction_elements.hybrid_shapes)\n",
    "selection.add(plane_XY)\n",
    "selection.add(plane_YZ)\n",
    "selection.add(plane_ZX)\n",
    "selection.vis_properties.set_show(1)    # 0 for show, 1 for hide\n",
    "selection.clear()\n",
    "\n",
    "# Saving the file to specified path \n",
    "document.save_as(r\"C:\\Project\\Python\\Product\\Helicopter.CATpart\", overwrite= True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 258,
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[258], line 15\u001b[0m\n\u001b[0;32m     13\u001b[0m part\u001b[38;5;241m.\u001b[39min_work_object \u001b[38;5;241m=\u001b[39m partbody\n\u001b[0;32m     14\u001b[0m time\u001b[38;5;241m.\u001b[39msleep(\u001b[38;5;241m0.25\u001b[39m)\n\u001b[1;32m---> 15\u001b[0m \u001b[43mdocument\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpart\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mupdate\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Project\\Python\\project_env\\Lib\\site-packages\\pycatia\\mec_mod_interfaces\\part.py:906\u001b[0m, in \u001b[0;36mPart.update\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    886\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mupdate\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    887\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m    888\u001b[0m \u001b[38;5;124;03m    .. note::\u001b[39;00m\n\u001b[0;32m    889\u001b[0m \u001b[38;5;124;03m        :class: toggle\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    904\u001b[0m \u001b[38;5;124;03m    :rtype: None\u001b[39;00m\n\u001b[0;32m    905\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m--> 906\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpart\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mUpdate\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m<COMObject <unknown>>:2\u001b[0m, in \u001b[0;36mUpdate\u001b[1;34m(self)\u001b[0m\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "# Rotating the blade and shaft animation\n",
    "\n",
    "# Show the magic\n",
    "# Rotate the body and blades\n",
    "for i in range(36):\n",
    "    shpfac.add_new_rotate2(z_dir, 10)\n",
    "    time.sleep(0.25)\n",
    "    document.part.update()\n",
    "\n",
    "while True:\n",
    "    part.in_work_object = blades\n",
    "    shpfac.add_new_rotate2(z_dir, 10)\n",
    "    part.in_work_object = partbody\n",
    "    time.sleep(0.25)\n",
    "    document.part.update()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "project_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
